spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    hikari:
      connection-timeout: 600_000
      idle-timeout: 600_000
      maximum-pool-size: 10
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  swagger-ui:
    path: /documentation.html